import JaxLean.Core.Tensor
import JaxLean.Core.RealOps
import examples.basics.generated.Matmul
import examples.basics.generated.Scan
import examples.basics.generated.Smooth
import examples.basics.proofs.Proofs
import examples.selection.proofs.Selection
import examples.random_program.proofs.RandomProgramProofs
import examples.monte_carlo.proofs.MonteCarloProofs
import examples.norms.proofs.NormProofs
import examples.certificates.proofs.Certificates
import examples.transformer.proofs.TransformerProofs
import examples.randint_monte_carlo.proofs.RandintMonteCarloProofs
import examples.tensor_puzzles.proofs.TensorPuzzleProofs
import examples.tensor_puzzles.proofs.TensorLoopProofs
import examples.scatter.proofs.ScatterProofs
import examples.common_primitives.proofs.CommonPrimitiveProofs
import examples.noether.proofs.NoetherProofs
import examples.tensor_puzzles.proofs.AllTensorPuzzles

import examples.autodiff.proofs.Jvp
